"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useState } from "react";
import ColorPicker from "@/components/color-picker";
import NavMenu from "@/components/navigation-menu";
import Footer from "@/components/footer";
import { themeOptions } from "@/lib/constants";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const themes = ["default", "dark", "orange"];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [themeColor, setThemeColor] = useState<string>(themeOptions[0]);

  const handleThemeChange = (newTheme: string) => {
    setThemeColor(newTheme);
  };

  return (
    <html lang="en">
      <body className={`${inter.className} ${themeColor}`}>
        <>
          {/* ------------------------ Theme Picker -------------------------*/}
          <div className="z-20">
            <ColorPicker
              themeSelected={themeColor}
              themeChange={handleThemeChange}
            />
          </div>

          {/* --------------------------- Navbar ---------------------------- */}
          <div className="top-[4.5rem] fixed border-solid border-2 border-indigo-600 w-full bg-indigo-500 z-20">
            <NavMenu />
          </div>

          {/* --------------------------- Children -------------------------- */}
          <div className="mt-32">{children}</div>

          {/* ---------------------------- Footer --------------------------- */}
          <div className="w-full bg-stone-700">
            <Footer />
          </div>
        </>
      </body>
    </html>
  );
}
