"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useState } from "react";
import ColorPicker from "@/components/color-picker";
import { themeOptions } from "@/lib/constants";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const themes = ["default", "dark", "orange"];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [themeColor, setThemeColor] = useState<string>(themeOptions[0]);

  const handleThemeChange = (newTheme: string) => {
    setThemeColor(newTheme);
  };

  return (
    <html lang="en">
      <body className={`${inter.className} ${themeColor}`}>
        <>
          {/* Theme Picker */}
          <div>
            <ColorPicker
              themeSelected={themeColor}
              themeChange={handleThemeChange}
            />
          </div>
          {/* Navbar */}
          <div className="flex gap-1 justify-normal align-middle top-[5.5rem] fixed border-solid border-2 border-indigo-600 w-full bg-slate-300">
            <h1>Navbar here</h1>
          </div>
          {/* Children */}
          <div className="mt-32">{children}</div>
        </>
      </body>
    </html>
  );
}
