"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useState } from "react";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const themes = ["default", "dark", "orange"];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [themeColor, setThemeColor] = useState<string>(themes[0]);

  return (
    <html lang="en">
      <body className={`${inter.className} ${themeColor}`}>
        <>
          <div className="flex gap-1 justify-normal align-middle">
            <h1>Header</h1>
            <h2>Logo</h2>
            <div>
              <h1>Theme Selctor</h1>
              {themes.map((t) => (
                <p key={t} onClick={() => setThemeColor(t)}>
                  {t}
                </p>
              ))}
            </div>
          </div>
          {children}
        </>
      </body>
    </html>
  );
}
